[supervisord]
nodaemon=true

[program:backend]
command=node backend/src/server.js
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ai-service]
command=uvicorn ai-service.src.app:app --host 0.0.0.0 --port 8000
directory=/app/ai-service
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:frontend]
command=npm start
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr